version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${POSTGRES_PORT}:5432"

  rasa:
    image: rasa/rasa:3.6.20-full
    container_name: rasa
    command: run --enable-api --cors "*" --debug
    depends_on:
      - postgres
      - rasa-actions
    volumes:
      - ./rasa:/app
    ports:
      - "5005:5005"
    env_file: .env

  rasa-actions:
    build:
      context: ./rasa
      dockerfile: Dockerfile.actions
    container_name: rasa-actions
    depends_on:
      - postgres
    volumes:
      - ./rasa/actions:/app/actions
    ports:
      - "5055:5055"
    env_file: .env

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

volumes:
  postgres_data:
  n8n_data: